@extends('patient-dashboard.patient-home')
@section('heading','Order Medicine')
@section('title','Order Medicine')
@section('content')
<div class="container" >
  <div class="row">
    <div class="col-md-12 box mar-top10 academic">
      {!!Form::open(['url'=>['order-confirm'],'method'=>'post', 'enctype'=>'multipart/form-data'])!!}

      <input type="hidden" name="txtHistoryID" value="{{$qPrescriptionDetails->pahiID}}">
      <div class="row">
        <div class="col-sm-1"> {{ Form::label('receiver-name', 'Name') }} <i class="fa fa-star text-danger" aria-hidden="true"></i> </div>
        <div class="col-sm-7">
          {{ Form::text('txtReceiverName',old("txtReceiverName"),['class'=>'form-control','maxlength'=>'69','placeholder' => 'Enter Receiver Name','required'])}}

          @if ($errors->has('txtReceiverName'))
          <span class="text-danger">
            <strong>{{ $errors->first('txtReceiverName') }}</strong>
          </span>
          @endif
        </div>
        <div class="col-sm-1"> {{ Form::label('phone-number', 'Phone') }} <i class="fa fa-star text-danger" aria-hidden="true"></i> </div>
        <div class="col-sm-3">
          {{ Form::text('txtPhoneNumber',old("txtPhoneNumber"),['class'=>'form-control','maxlength'=>'69','placeholder' => 'Enter a Valid Phone Number','required'])}}

          @if ($errors->has('txtPhoneNumber'))
          <span class="text-danger">
            <strong>{{ $errors->first('txtPhoneNumber') }}</strong>
          </span>
          @endif
        </div>
      </div>
      <br>
      <div class="row">
        <div class="col-sm-1"> {{ Form::label('address', 'Address') }} <i class="fa fa-star text-danger" aria-hidden="true"></i></div>
        <div class="col-sm-11">
          {{ Form::text('txtAddress',old("txtAddress"),['class'=>'form-control','placeholder' => 'Shipping Address','required'])}}

          @if ($errors->has('txtAddress'))
          <span class="text-danger">
            <strong>{{ $errors->first('txtAddress') }}</strong>
          </span>
          @endif
        </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pull-right">
    {{Form::submit('Confirm',['class'=>'btn btn-block btn-success'])}}
  </div>

  
  <span style="font-size:2.5em;">{{$qPrescriptionDetails->dName}}</span>
  <br />
  <span style="font-size:1.2em;">
    {{$qPrescriptionDetails->degree}}<br />
    {{$qPrescriptionDetails->training}}<br />
    <strong style="color: green;">GK Pharma (Unani) Limited</strong>
  </span>

  <div class="row" style="padding:5px 0px px 0px;border-top:1px solid black;border-bottom:1px solid black;">
    <div class="col-sm-5" style="border-right:1px solid black;">Name : {{$qPrescriptionDetails->pName}}</div>
    <div class="col-sm-2" style="border-right:1px solid black;">Age : {{$qPrescriptionDetails->age}}</div>
    <div class="col-sm-2" style="border-right:1px solid black;">Sex : {{$qPrescriptionDetails->gender}}</div>
    <div class="col-sm-3">Date : {{date("d M, Y", strtotime ($qPrescriptionDetails->created_at))}}</div>
  </div>

  <div class="row">
    <!-- Left Side -->
    <div class="col-sm-3" style="font-size:1.2em;padding-top:5px;">
      Bp: {{$qPrescriptionDetails->bp}}
      <br />
      Other Note
    </div>
    <!-- Right Side -->
    <div class="col-sm-9" style="min-height:400px;font-size:1.2em;padding-top:5px;border-left:1px solid black;">
      <?php
      $sl = 1;
      ?>
      @foreach($qMedicine as $sMedicine)

      <div style="margin: 20px 0px 10px 20px;">
        <span>{{$sl++}}. <input type="hidden" name="proName[]" value="{{$sMedicine->id}}"> {{$sMedicine->proName}}</span><br>
        <div style="margin-left: 20px;">
          <span>{{$sMedicine->dose_time}}</span><br>
          <span>{{$sMedicine->dose_qty}}</span> <span style="margin-right: 20px;">{{$sMedicine->dose_qty_type}} করে {{$sMedicine->dose_eat}}</span> <span>{{$sMedicine->dose_duration}}</span> <span>{{$sMedicine->dose_duration_type}}</span>
          <br><br>
        </div>

      </div>
      @endforeach
    </div>
  </div>
  {!! Form::close() !!}
  <!-- Prescription Footer -->

  <div class="row text-center" style="border-top:1px solid black;padding:5px; font-weight: bold;">
    <b> বিঃ দ্রঃ </b> টক-ঝাল, ভাজা-পোড়া, পচা ও বাসি খাবার খাওয়া নিষেধ।
  </div>
  <div class="row text-center" style="border-top:1px solid black;padding:5px;">
    This is computer generated Prescription.Generated by <a href="http://doctorplease.com.bd">doctorplease.com.bd</a>
  </div>
</div>

@endsection

@push('scripts')

@endpush
