@extends('patient-dashboard.patient-home')
@section('heading','Order Medicine')
@section('title',' Patient Prescription')
@section('content')
<div class="container" >
  <div class="row text-right">
    <a charset="UTF-8" class="btn btn-success" href="{{url('order/'.$qPrescriptionDetails->pahiID)}}">Order Medicine</a>
  <a charset="UTF-8" style="margin-right: 10px;" class="btn btn-info" href="{{url('pdf/'.$qPrescriptionDetails->pahiID)}}">Download Prescription</a>
  </div>
  <br>
  <div class="row box">
      <span style="font-size:2.5em;">{{$qPrescriptionDetails->dName}}</span>
      <br />
      <span style="font-size:1.2em;">
        {{$qPrescriptionDetails->degree}}<br />
        {{$qPrescriptionDetails->training}}<br />
        <strong style="color: green;">GK Pharma (Unani) Limited</strong>
      </span>
    
    <div class="row" style="padding:5px 0px px 0px;border-top:1px solid black;border-bottom:1px solid black;">
      <div class="col-sm-5" style="border-right:1px solid black;">Name : {{$qPrescriptionDetails->pName}}</div>
      <div class="col-sm-2" style="border-right:1px solid black;">Age : {{$qPrescriptionDetails->age}}</div>
      <div class="col-sm-2" style="border-right:1px solid black;">Sex : {{$qPrescriptionDetails->gender}}</div>
      <div class="col-sm-3">Date : {{date("d M, Y", strtotime ($qPrescriptionDetails->created_at))}}</div>
    </div>

    <div class="row">
      <!-- Left Side -->
      <div class="col-sm-3" style="font-size:1.2em;padding-top:5px;">
        Bp: {{$qPrescriptionDetails->bp}}
        <br />
        Other Note
      </div>
      <!-- Right Side -->
      <div class="col-sm-9" style="min-height:400px;font-size:1.2em;padding-top:5px;border-left:1px solid black;">
        <?php
          $sl = 1;
        ?>
          @foreach($qMedicine as $sMedicine)

            <div style="margin: 20px 0px 10px 20px;">
              <span>{{$sl++}}. {{$sMedicine->proName}}</span><br>
              <div style="margin-left: 20px;">
                <span>{{$sMedicine->dose_time}}</span><br>
                <span>{{$sMedicine->dose_qty}}</span> <span style="margin-right: 20px;">{{$sMedicine->dose_qty_type}} করে {{$sMedicine->dose_eat}}</span> <span>{{$sMedicine->dose_duration}}</span> <span>{{$sMedicine->dose_duration_type}}</span>
              </div>

            </div>
          @endforeach
      </div>
    </div>
    <!-- Prescription Footer -->

    <div class="row text-center" style="border-top:1px solid black;padding:5px; font-weight: bold;">
     <b> বিঃ দ্রঃ </b> টক-ঝাল, ভাজা-পোড়া, পচা ও বাসি খাবার খাওয়া নিষেধ।
    </div>
    <div class="row text-center" style="border-top:1px solid black;padding:5px;">
      This is computer generated Prescription.Generated by <a href="http://doctorplease.com.bd">doctorplease.com.bd</a>
    </div>
  </div>
</div>

@endsection

@push('scripts')

@endpush
