<template>
    <div id="app">
      <div class="panel form-element-padding">
        <div class="panel-body">
          <div class="col-md-12">
            <div class="row">
              <span style="font-size:2.5em;">Dr. Sohel Ahmed</span><br />
              <span style="font-size:1.2em;">
                BAMS (Bachelor of Ayurvedic Medicine & Surgery)<br />
                General Physician Reg.no-257<br />
                Expart in skin,sex,gastrointestinal diseases & Herbal medicien<br />
                <strong>GK Pharma (Unani) Limited</strong>
              </span>
            </div>

            <div class="row" style="padding:5px 0px 5px 0px;border-top:1px solid black;border-bottom:1px solid black;">
              <div class="col-sm-5" style="border-right:1px solid black;">Name : Mohammad Saiful Islam</div>
              <div class="col-sm-2" style="border-right:1px solid black;">Age : 199</div>
              <div class="col-sm-2" style="border-right:1px solid black;">Sex : Male</div>
              <div class="col-sm-3">Date : 31 July, 2018
                <!-- <button class="btn btn-secondery btn-sm pull-right addRow">+</abutton> -->
              </div>
            </div>

            <div class="row">
              <div class="col-sm-2" style="font-size:1.2em;padding-top:5px;">
                Bp<br />Other Note

                <div class="row">
                  <div class="col-sm-12 col-md-12">
                    <textarea class="form-control col-md-12 col-sm-12" style="min-height: 100px;"></textarea>
                    <button class="submit btn btn-primary btn-block">Comments</button>
                  </div>
                </div>
              </div>
              <div class="col-sm-10" style="min-height:400px;font-size:1.2em;padding-top:5px;border-left:1px solid black;">

              </div>
            </div>
            <!-- Prescription Footer -->
            <div class="row text-center" style="border-top:1px solid black;padding:5px;">
              This is computer generated Prescription.Generated by doctorplease.com.bd
            </div>
            <div class="col-sm-12">
            </div>
          </div>
        </div>
      </div>
    </div>
</template>

<script>
    export default {
        mounted() {
            console.log('Component mounted.')
        }
    }
</script>
