<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <link href="{{url('css/bootstrap.css')}}" rel="stylesheet">
  <link href="{{url('css/style.css')}}" rel="stylesheet">
  <!-- Responsive -->
  <link href="{{url('css/responsive.css')}}" rel="stylesheet">
</head>
<style>
body{
  padding: 60px 10px 10px 30px;
  box-sizing: content-box;
}
@font-face {
  font-family: SolaimanLipi;
  font-style: normal;
  font-weight: 400;
  src: url({{asset('fonts/SolaimanLipi.ttf')}});
}

</style>
<body>
  <div class="container">
    <div class="row">
      <span style="font-size:2.5em;">{{$qPrescriptionDetails->dName}}</span>
      <br />
      <span style="font-size:1.2em;">
        {{$qPrescriptionDetails->degree}}<br />
        {{$qPrescriptionDetails->training}}<br />
        <strong style="color: green;">GK Pharma (Unani) Limited</strong>
      </span>
    </div>

    <div class="row" style="padding:0px 5px 5px 0px;border-top:1px solid black;border-bottom:1px solid black;">
      <div class="col-sm-4" style="border-right:1px solid black;">Name : {{$qPrescriptionDetails->pName}}</div>
      <div class="col-sm-2" style="border-right:1px solid black;">Age : {{$qPrescriptionDetails->age}}</div>
      <div class="col-sm-2" style="border-right:1px solid black;">Sex : {{$qPrescriptionDetails->gender}}</div>
      <div class="col-sm-3">Date : {{date("d M, Y", strtotime ($qPrescriptionDetails->created_at))}}</div>
    </div>

    <div class="row">
      <!-- Left Side -->
      <div class="col-sm-3" style="font-size:1.2em;padding-top:5px;">
        Bp: {{$qPrescriptionDetails->bp}}
        <br />
        Other Note
      </div>
      <!-- Right Side -->
      <div class="col-sm-9" style="min-height:400px;font-size:1.2em;padding-top:5px;border-left:1px solid black;">
        <?php
        $sl = 1;
        ?>
        @foreach($qMedicine as $sMedicine)

        <div style="margin: 20px 0px 10px 20px;">
          <span>{{$sl++}}. {{$sMedicine->proName}}</span><br>
          <div style="margin-left: 20px;">
            <span>{{$sMedicine->dose_time}}</span><br>
            <span>{{$sMedicine->dose_qty}}</span> <span style="margin-right: 20px;">{{$sMedicine->dose_qty_type}} করে {{$sMedicine->dose_eat}}</span> <span>{{$sMedicine->dose_duration}}</span> <span>{{$sMedicine->dose_duration_type}}</span>
          </div>
        </div>
        @endforeach
      </div>
    </div>
    <!-- Prescription Footer -->

    <div class="row text-center font" style="border-top:1px solid black;padding:5px; font-weight: bold;">
      <b> বিঃ দ্রঃ </b>  টক-ঝাল, ভাজা-পোড়া, পচা ও বাসি খাবার খাওয়া নিষেধ।
    </div>
    <div class="row text-center" style="border-top:1px solid black;padding:5px;">
      This is computer generated Prescription.Generated by <a href="http://doctorplease.com.bd">doctorplease.com.bd</a>
    </div>
  </div>
</body>
</html>